swagger: "2.0"
info:
 description: This is the swagger file that goes with our server code
 version: "1.0.0"
 title: Swagger ReST Article
consumes:
 - application/json
produces:
 - application/json

basePath: /api

# Paths supported by the server application
paths:
 /market:
   get:
     operationId: items.read_all
     tags:
       - Items
     summary: Read the entire list of items
     description: Read the list of items
     parameters:
       - name: length
         in: query
         type: integer
         description: Number of items to get from items
         required: false
       - name: offset
         in: query
         type: integer
         description: Offset from beginning of list where to start gathering items
         required: false
     responses:
       200:
         description: Successfully read items list operation
         schema:
           type: array
           items:
             properties:
               fname:
                 type: string
               lname:
                 type: string
               timestamp:
                 type: string

